import type { LessonProgram } from '../../types';

export const factorial_func: LessonProgram = {
  id: 'factorial_func', language: 'python', topic: 'functions', lessonNumber: 9,
  friendlyName: 'Factorial Using Function',
  learningObjective: 'Learn to use loops inside a function to compute a value and return it.',
  lines: [
    { lineNum: 1, tokens: [{ type: 'keyword', value: 'def' }, { type: 'text', value: ' ' }, { type: 'function', value: 'factorial' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'n' }, { type: 'punctuation', value: ')' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 2, tokens: [{ type: 'text', value: '    ' }, { type: 'variable', value: 'result' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }] },
    { lineNum: 3, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'for' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'i' }, { type: 'text', value: ' ' }, { type: 'keyword', value: 'in' }, { type: 'text', value: ' ' }, { type: 'function', value: 'range' }, { type: 'punctuation', value: '(' }, { type: 'number', value: '1' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'n' }, { type: 'text', value: ' ' }, { type: 'operator', value: '+' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }, { type: 'punctuation', value: ')' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 4, tokens: [{ type: 'text', value: '        ' }, { type: 'variable', value: 'result' }, { type: 'text', value: ' ' }, { type: 'operator', value: '*=' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'i' }] },
    { lineNum: 5, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'return' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'result' }] },
    { lineNum: 6, tokens: [{ type: 'text', value: '' }] },
    { lineNum: 7, tokens: [{ type: 'variable', value: 'num' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'number', value: '4' }] },
    { lineNum: 8, tokens: [{ type: 'variable', value: 'fact_val' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'function', value: 'factorial' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'num' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 9, tokens: [{ type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'fact_val' }, { type: 'punctuation', value: ')' }] },
  ],
  executionSteps: [
    {
      step: 1, lineNum: 1,
      explanationEnglish: 'Define a function to calculate the factorial of a number.',
      explanationHinglish: 'Factorial nikalne ke liye function define kiya.',
      memorySnapshot: {},
      animationEvent: { type: 'NONE' },
    },
    {
      step: 2, lineNum: 7,
      explanationEnglish: 'Set num = 4.',
      explanationHinglish: 'num mein 4 store kiya.',
      memorySnapshot: { num: 4 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'num', value: 4 },
    },
    {
      step: 3, lineNum: 8,
      explanationEnglish: 'Call the factorial function with num (4).',
      explanationHinglish: 'factorial(4) ko call kiya.',
      memorySnapshot: { num: 4 },
      animationEvent: { type: 'NONE' },
    },
    {
      step: 4, lineNum: 1,
      explanationEnglish: 'The parameter n receives the value 4.',
      explanationHinglish: 'Parameter n ko 4 found hua.',
      memorySnapshot: { num: 4, n: 4 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 4 },
    },
    {
      step: 5, lineNum: 2,
      explanationEnglish: 'Initialize result to 1.',
      explanationHinglish: 'result ko 1 se start kiya.',
      memorySnapshot: { num: 4, n: 4, result: 1 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'result', value: 1 },
    },
    {
      step: 6, lineNum: 3,
      explanationEnglish: 'Loop starts for i = 1.',
      explanationHinglish: 'Loop execute hoega jab i = 1 hoga.',
      memorySnapshot: { num: 4, n: 4, result: 1, i: 1 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 1 },
    },
    {
      step: 7, lineNum: 4,
      explanationEnglish: 'Multiply result (1) by i (1). New result = 1.',
      explanationHinglish: 'result (1) ko i (1) se multiply kiya. Naya result 1.',
      memorySnapshot: { num: 4, n: 4, result: 1, i: 1 },
      animationEvent: { type: 'COMPUTE', inputs: ['result', 'i'], operator: '*', result: 1, storeIn: 'result' },
    },
    {
      step: 8, lineNum: 3,
      explanationEnglish: 'Loop starts for i = 2.',
      explanationHinglish: 'Loop execute hoega jab i = 2 hoga.',
      memorySnapshot: { num: 4, n: 4, result: 1, i: 2 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 2 },
    },
    {
      step: 9, lineNum: 4,
      explanationEnglish: 'Multiply result (1) by i (2). New result = 2.',
      explanationHinglish: 'result (1) ko i (2) se multiply kiya. Naya result 2.',
      memorySnapshot: { num: 4, n: 4, result: 2, i: 2 },
      animationEvent: { type: 'COMPUTE', inputs: ['result', 'i'], operator: '*', result: 2, storeIn: 'result' },
    },
    {
      step: 10, lineNum: 3,
      explanationEnglish: 'Loop starts for i = 3.',
      explanationHinglish: 'Loop execute hoega jab i = 3 hoga.',
      memorySnapshot: { num: 4, n: 4, result: 2, i: 3 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 3 },
    },
    {
      step: 11, lineNum: 4,
      explanationEnglish: 'Multiply result (2) by i (3). New result = 6.',
      explanationHinglish: 'result (2) ko i (3) se multiply kiya. Naya result 6.',
      memorySnapshot: { num: 4, n: 4, result: 6, i: 3 },
      animationEvent: { type: 'COMPUTE', inputs: ['result', 'i'], operator: '*', result: 6, storeIn: 'result' },
    },
    {
      step: 12, lineNum: 3,
      explanationEnglish: 'Loop starts for i = 4.',
      explanationHinglish: 'Loop execute hoega jab i = 4 hoga.',
      memorySnapshot: { num: 4, n: 4, result: 6, i: 4 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 4 },
    },
    {
      step: 13, lineNum: 4,
      explanationEnglish: 'Multiply result (6) by i (4). New result = 24.',
      explanationHinglish: 'result (6) ko i (4) se multiply kiya. Naya result 24.',
      memorySnapshot: { num: 4, n: 4, result: 24, i: 4 },
      animationEvent: { type: 'COMPUTE', inputs: ['result', 'i'], operator: '*', result: 24, storeIn: 'result' },
    },
    {
      step: 14, lineNum: 5,
      explanationEnglish: 'Return the final result (24).',
      explanationHinglish: 'Final result (24) wapas bheja.',
      memorySnapshot: { num: 4, n: 4, result: 24, i: 4 },
      animationEvent: { type: 'COMPUTE', inputs: [], operator: 'return', result: 24, storeIn: 'ReturnValue' },
    },
    {
      step: 15, lineNum: 8,
      explanationEnglish: 'Store the returned value in fact_val.',
      explanationHinglish: 'Wapas aayi value ko fact_val mein store kiya.',
      memorySnapshot: { num: 4, fact_val: 24 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'fact_val', value: 24 },
    },
    {
      step: 16, lineNum: 9,
      explanationEnglish: 'Print the computed factorial.',
      explanationHinglish: 'Factorial print kiya.',
      memorySnapshot: { num: 4, fact_val: 24 },
      consoleOutput: '24',
      animationEvent: { type: 'PRINT_VALUE', variableName: 'fact_val', outputValue: 24 },
    }
  ],
};