import type { LessonProgram } from '../../types';

export const multiplication_table: LessonProgram = {
  id: 'multiplication_table', language: 'python', topic: 'for_loop', lessonNumber: 5,
  friendlyName: 'Multiplication Table',
  learningObjective: 'Learn how to generate a multiplication table using a loop.',
  lines: [
    { lineNum: 1, tokens: [{ type: 'variable', value: 'num' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'number', value: '4' }] },
    { lineNum: 2, tokens: [{ type: 'keyword', value: 'for' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'i' }, { type: 'text', value: ' ' }, { type: 'keyword', value: 'in' }, { type: 'text', value: ' ' }, { type: 'function', value: 'range' }, { type: 'punctuation', value: '(' }, { type: 'number', value: '1' }, { type: 'punctuation', value: ',' }, { type: 'text', value: ' ' }, { type: 'number', value: '11' }, { type: 'punctuation', value: ')' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 3, tokens: [{ type: 'text', value: '    ' }, { type: 'variable', value: 'res' }, { type: 'text', value: ' ' }, { type: 'operator', value: '=' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'num' }, { type: 'text', value: ' ' }, { type: 'operator', value: '*' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'i' }] },
    { lineNum: 4, tokens: [{ type: 'text', value: '    ' }, { type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'res' }, { type: 'punctuation', value: ')' }] },
  ],
  executionSteps: [
    {
      step: 1, lineNum: 1,
      explanationEnglish: 'Store the table number in "num".',
      explanationHinglish: '"num" variable me table number dala.',
      memorySnapshot: { num: 4 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'num', value: 4 },
    },
    {
      step: 2, lineNum: 2,
      explanationEnglish: 'Loop starts for multiplier i = 1.',
      explanationHinglish: 'Loop i = 1 ke liye chalu hua.',
      memorySnapshot: { num: 4, i: 1 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 1 },
    },
    {
      step: 3, lineNum: 3,
      explanationEnglish: 'Calculate 4 * 1 = 4.',
      explanationHinglish: 'Multiply kiya: 4 * 1 = 4.',
      memorySnapshot: { num: 4, i: 1, res: 4 },
      animationEvent: { type: 'COMPUTE', inputs: ['num', 'i'], operator: '*', result: 4, storeIn: 'res' },
    },
    {
      step: 4, lineNum: 4,
      explanationEnglish: 'Print the result 4.',
      explanationHinglish: 'Result 4 print kiya.',
      memorySnapshot: { num: 4, i: 1, res: 4 },
      consoleOutput: `4`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'res', outputValue: 4 },
    },
    {
      step: 5, lineNum: 2,
      explanationEnglish: 'Loop starts for multiplier i = 2.',
      explanationHinglish: 'Loop i = 2 ke liye chalu hua.',
      memorySnapshot: { num: 4, i: 2 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 2 },
    },
    {
      step: 6, lineNum: 3,
      explanationEnglish: 'Calculate 4 * 2 = 8.',
      explanationHinglish: 'Multiply kiya: 4 * 2 = 8.',
      memorySnapshot: { num: 4, i: 2, res: 8 },
      animationEvent: { type: 'COMPUTE', inputs: ['num', 'i'], operator: '*', result: 8, storeIn: 'res' },
    },
    {
      step: 7, lineNum: 4,
      explanationEnglish: 'Print the result 8.',
      explanationHinglish: 'Result 8 print kiya.',
      memorySnapshot: { num: 4, i: 2, res: 8 },
      consoleOutput: `4\n8`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'res', outputValue: 8 },
    },
    {
      step: 8, lineNum: 2,
      explanationEnglish: 'Loop starts for multiplier i = 3.',
      explanationHinglish: 'Loop i = 3 ke liye chalu hua.',
      memorySnapshot: { num: 4, i: 3 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 3 },
    },
    {
      step: 9, lineNum: 3,
      explanationEnglish: 'Calculate 4 * 3 = 12.',
      explanationHinglish: 'Multiply kiya: 4 * 3 = 12.',
      memorySnapshot: { num: 4, i: 3, res: 12 },
      animationEvent: { type: 'COMPUTE', inputs: ['num', 'i'], operator: '*', result: 12, storeIn: 'res' },
    },
    {
      step: 10, lineNum: 4,
      explanationEnglish: 'Print the result 12.',
      explanationHinglish: 'Result 12 print kiya.',
      memorySnapshot: { num: 4, i: 3, res: 12 },
      consoleOutput: `4\n8\n12`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'res', outputValue: 12 },
    },
    {
      step: 11, lineNum: 2,
      explanationEnglish: 'Loop starts for multiplier i = 4.',
      explanationHinglish: 'Loop i = 4 ke liye chalu hua.',
      memorySnapshot: { num: 4, i: 4 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 4 },
    },
    {
      step: 12, lineNum: 3,
      explanationEnglish: 'Calculate 4 * 4 = 16.',
      explanationHinglish: 'Multiply kiya: 4 * 4 = 16.',
      memorySnapshot: { num: 4, i: 4, res: 16 },
      animationEvent: { type: 'COMPUTE', inputs: ['num', 'i'], operator: '*', result: 16, storeIn: 'res' },
    },
    {
      step: 13, lineNum: 4,
      explanationEnglish: 'Print the result 16.',
      explanationHinglish: 'Result 16 print kiya.',
      memorySnapshot: { num: 4, i: 4, res: 16 },
      consoleOutput: `4\n8\n12\n16`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'res', outputValue: 16 },
    },
    {
      step: 14, lineNum: 2,
      explanationEnglish: 'Loop starts for multiplier i = 5.',
      explanationHinglish: 'Loop i = 5 ke liye chalu hua.',
      memorySnapshot: { num: 4, i: 5 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 5 },
    },
    {
      step: 15, lineNum: 3,
      explanationEnglish: 'Calculate 4 * 5 = 20.',
      explanationHinglish: 'Multiply kiya: 4 * 5 = 20.',
      memorySnapshot: { num: 4, i: 5, res: 20 },
      animationEvent: { type: 'COMPUTE', inputs: ['num', 'i'], operator: '*', result: 20, storeIn: 'res' },
    },
    {
      step: 16, lineNum: 4,
      explanationEnglish: 'Print the result 20.',
      explanationHinglish: 'Result 20 print kiya.',
      memorySnapshot: { num: 4, i: 5, res: 20 },
      consoleOutput: `4\n8\n12\n16\n20`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'res', outputValue: 20 },
    },
    {
      step: 17, lineNum: 2,
      explanationEnglish: 'Loop starts for multiplier i = 6.',
      explanationHinglish: 'Loop i = 6 ke liye chalu hua.',
      memorySnapshot: { num: 4, i: 6 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 6 },
    },
    {
      step: 18, lineNum: 3,
      explanationEnglish: 'Calculate 4 * 6 = 24.',
      explanationHinglish: 'Multiply kiya: 4 * 6 = 24.',
      memorySnapshot: { num: 4, i: 6, res: 24 },
      animationEvent: { type: 'COMPUTE', inputs: ['num', 'i'], operator: '*', result: 24, storeIn: 'res' },
    },
    {
      step: 19, lineNum: 4,
      explanationEnglish: 'Print the result 24.',
      explanationHinglish: 'Result 24 print kiya.',
      memorySnapshot: { num: 4, i: 6, res: 24 },
      consoleOutput: `4\n8\n12\n16\n20\n24`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'res', outputValue: 24 },
    },
    {
      step: 20, lineNum: 2,
      explanationEnglish: 'Loop starts for multiplier i = 7.',
      explanationHinglish: 'Loop i = 7 ke liye chalu hua.',
      memorySnapshot: { num: 4, i: 7 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 7 },
    },
    {
      step: 21, lineNum: 3,
      explanationEnglish: 'Calculate 4 * 7 = 28.',
      explanationHinglish: 'Multiply kiya: 4 * 7 = 28.',
      memorySnapshot: { num: 4, i: 7, res: 28 },
      animationEvent: { type: 'COMPUTE', inputs: ['num', 'i'], operator: '*', result: 28, storeIn: 'res' },
    },
    {
      step: 22, lineNum: 4,
      explanationEnglish: 'Print the result 28.',
      explanationHinglish: 'Result 28 print kiya.',
      memorySnapshot: { num: 4, i: 7, res: 28 },
      consoleOutput: `4\n8\n12\n16\n20\n24\n28`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'res', outputValue: 28 },
    },
    {
      step: 23, lineNum: 2,
      explanationEnglish: 'Loop starts for multiplier i = 8.',
      explanationHinglish: 'Loop i = 8 ke liye chalu hua.',
      memorySnapshot: { num: 4, i: 8 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 8 },
    },
    {
      step: 24, lineNum: 3,
      explanationEnglish: 'Calculate 4 * 8 = 32.',
      explanationHinglish: 'Multiply kiya: 4 * 8 = 32.',
      memorySnapshot: { num: 4, i: 8, res: 32 },
      animationEvent: { type: 'COMPUTE', inputs: ['num', 'i'], operator: '*', result: 32, storeIn: 'res' },
    },
    {
      step: 25, lineNum: 4,
      explanationEnglish: 'Print the result 32.',
      explanationHinglish: 'Result 32 print kiya.',
      memorySnapshot: { num: 4, i: 8, res: 32 },
      consoleOutput: `4\n8\n12\n16\n20\n24\n28\n32`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'res', outputValue: 32 },
    },
    {
      step: 26, lineNum: 2,
      explanationEnglish: 'Loop starts for multiplier i = 9.',
      explanationHinglish: 'Loop i = 9 ke liye chalu hua.',
      memorySnapshot: { num: 4, i: 9 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 9 },
    },
    {
      step: 27, lineNum: 3,
      explanationEnglish: 'Calculate 4 * 9 = 36.',
      explanationHinglish: 'Multiply kiya: 4 * 9 = 36.',
      memorySnapshot: { num: 4, i: 9, res: 36 },
      animationEvent: { type: 'COMPUTE', inputs: ['num', 'i'], operator: '*', result: 36, storeIn: 'res' },
    },
    {
      step: 28, lineNum: 4,
      explanationEnglish: 'Print the result 36.',
      explanationHinglish: 'Result 36 print kiya.',
      memorySnapshot: { num: 4, i: 9, res: 36 },
      consoleOutput: `4\n8\n12\n16\n20\n24\n28\n32\n36`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'res', outputValue: 36 },
    },
    {
      step: 29, lineNum: 2,
      explanationEnglish: 'Loop starts for multiplier i = 10.',
      explanationHinglish: 'Loop i = 10 ke liye chalu hua.',
      memorySnapshot: { num: 4, i: 10 },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'i', value: 10 },
    },
    {
      step: 30, lineNum: 3,
      explanationEnglish: 'Calculate 4 * 10 = 40.',
      explanationHinglish: 'Multiply kiya: 4 * 10 = 40.',
      memorySnapshot: { num: 4, i: 10, res: 40 },
      animationEvent: { type: 'COMPUTE', inputs: ['num', 'i'], operator: '*', result: 40, storeIn: 'res' },
    },
    {
      step: 31, lineNum: 4,
      explanationEnglish: 'Print the result 40.',
      explanationHinglish: 'Result 40 print kiya.',
      memorySnapshot: { num: 4, i: 10, res: 40 },
      consoleOutput: `4\n8\n12\n16\n20\n24\n28\n32\n36\n40`,
      animationEvent: { type: 'PRINT_VALUE', variableName: 'res', outputValue: 40 },
    }
  ],
};