import type { LessonProgram } from '../../types';

export const recursive_print_n: LessonProgram = {
  id: 'recursive_print_n', language: 'python', topic: 'recursion', lessonNumber: 1,
  friendlyName: 'Print Numbers 1 to N',
  learningObjective: 'Visualize how a recursive function calls itself and builds a call stack.',
  lines: [
    { lineNum: 1, tokens: [{ type: 'keyword', value: 'def' }, { type: 'text', value: ' ' }, { type: 'function', value: 'print_n' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'n' }, { type: 'punctuation', value: ')' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 2, tokens: [{ type: 'text', value: '    ' }, { type: 'keyword', value: 'if' }, { type: 'text', value: ' ' }, { type: 'variable', value: 'n' }, { type: 'text', value: ' ' }, { type: 'operator', value: '==' }, { type: 'text', value: ' ' }, { type: 'number', value: '0' }, { type: 'punctuation', value: ':' }] },
    { lineNum: 3, tokens: [{ type: 'text', value: '        ' }, { type: 'keyword', value: 'return' }] },
    { lineNum: 4, tokens: [{ type: 'text', value: '    ' }, { type: 'function', value: 'print_n' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'n' }, { type: 'text', value: ' ' }, { type: 'operator', value: '-' }, { type: 'text', value: ' ' }, { type: 'number', value: '1' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 5, tokens: [{ type: 'text', value: '    ' }, { type: 'function', value: 'print' }, { type: 'punctuation', value: '(' }, { type: 'variable', value: 'n' }, { type: 'punctuation', value: ')' }] },
    { lineNum: 6, tokens: [{ type: 'function', value: 'print_n' }, { type: 'punctuation', value: '(' }, { type: 'number', value: '3' }, { type: 'punctuation', value: ')' }] },
  ],
  executionSteps: [
    {
      step: 1, lineNum: 1,
      explanationEnglish: 'Define a recursive function to print numbers from 1 to N.',
      explanationHinglish: 'Recursion ka use karke 1 se N tak print karne ke liye function banaya.',
      memorySnapshot: {},
      animationEvent: { type: 'NONE' },
    },
    {
      step: 2, lineNum: 6,
      explanationEnglish: 'Call print_n(3).',
      explanationHinglish: 'print_n(3) ko call kiya.',
      memorySnapshot: { CallStack: 'print_n(3)' },
      animationEvent: { type: 'NONE' },
    },
    {
      step: 3, lineNum: 1,
      explanationEnglish: 'Entered print_n with n = 3.',
      explanationHinglish: 'print_n function mein n = 3 ke sath enter kiya.',
      memorySnapshot: { n: 3, CallStack: 'print_n(3)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 3 },
    },
    {
      step: 4, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (3) == 0?',
      explanationHinglish: 'Check kiya kya n (3) == 0 hai?',
      memorySnapshot: { n: 3, CallStack: 'print_n(3)' },
      animationEvent: { type: 'COMPUTE', inputs: ['n', '0'], operator: '==', formula: 'n == 0', result: 'False', storeIn: 'Condition' },
    },
    {
      step: 5, lineNum: 4,
      explanationEnglish: 'Call print_n(2) recursively. (Push to Stack)',
      explanationHinglish: 'Recursion: print_n(2) ko call kiya. (Stack Push)',
      memorySnapshot: { n: 3, CallStack: 'print_n(3) -> print_n(2)' },
      animationEvent: { type: 'FUNCTION_CALL', functionName: 'print_n', args: { n: 2 } },
    },
    {
      step: 6, lineNum: 1,
      explanationEnglish: 'Entered print_n with n = 2.',
      explanationHinglish: 'print_n function mein n = 2 ke sath enter kiya.',
      memorySnapshot: { n: 2, CallStack: 'print_n(3) -> print_n(2)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 2 },
    },
    {
      step: 7, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (2) == 0?',
      explanationHinglish: 'Check kiya kya n (2) == 0 hai?',
      memorySnapshot: { n: 2, CallStack: 'print_n(3) -> print_n(2)' },
      animationEvent: { type: 'COMPUTE', inputs: ['n', '0'], operator: '==', formula: 'n == 0', result: 'False', storeIn: 'Condition' },
    },
    {
      step: 8, lineNum: 4,
      explanationEnglish: 'Call print_n(1) recursively. (Push to Stack)',
      explanationHinglish: 'Recursion: print_n(1) ko call kiya. (Stack Push)',
      memorySnapshot: { n: 2, CallStack: 'print_n(3) -> print_n(2) -> print_n(1)' },
      animationEvent: { type: 'FUNCTION_CALL', functionName: 'print_n', args: { n: 1 } },
    },
    {
      step: 9, lineNum: 1,
      explanationEnglish: 'Entered print_n with n = 1.',
      explanationHinglish: 'print_n function mein n = 1 ke sath enter kiya.',
      memorySnapshot: { n: 1, CallStack: 'print_n(3) -> print_n(2) -> print_n(1)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 1 },
    },
    {
      step: 10, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (1) == 0?',
      explanationHinglish: 'Check kiya kya n (1) == 0 hai?',
      memorySnapshot: { n: 1, CallStack: 'print_n(3) -> print_n(2) -> print_n(1)' },
      animationEvent: { type: 'COMPUTE', inputs: ['n', '0'], operator: '==', formula: 'n == 0', result: 'False', storeIn: 'Condition' },
    },
    {
      step: 11, lineNum: 4,
      explanationEnglish: 'Call print_n(0) recursively. (Push to Stack)',
      explanationHinglish: 'Recursion: print_n(0) ko call kiya. (Stack Push)',
      memorySnapshot: { n: 1, CallStack: 'print_n(3) -> print_n(2) -> print_n(1) -> print_n(0)' },
      animationEvent: { type: 'FUNCTION_CALL', functionName: 'print_n', args: { n: 0 } },
    },
    {
      step: 12, lineNum: 1,
      explanationEnglish: 'Entered print_n with n = 0.',
      explanationHinglish: 'print_n function mein n = 0 ke sath enter kiya.',
      memorySnapshot: { n: 0, CallStack: 'print_n(3) -> print_n(2) -> print_n(1) -> print_n(0)' },
      animationEvent: { type: 'CREATE_VARIABLE', name: 'n', value: 0 },
    },
    {
      step: 13, lineNum: 2,
      explanationEnglish: 'Check base condition: is n (0) == 0?',
      explanationHinglish: 'Check kiya kya n (0) == 0 hai?',
      memorySnapshot: { n: 0, CallStack: 'print_n(3) -> print_n(2) -> print_n(1) -> print_n(0)' },
      animationEvent: { type: 'COMPUTE', inputs: ['n', '0'], operator: '==', formula: 'n == 0', result: 'True', storeIn: 'Condition' },
    },
    {
      step: 14, lineNum: 3,
      explanationEnglish: 'Base condition met! Return to previous call.',
      explanationHinglish: 'Base condition mil gayi! Wapas return karo.',
      memorySnapshot: { n: 0, CallStack: 'print_n(3) -> print_n(2) -> print_n(1) -> print_n(0)' },
      animationEvent: { type: 'FUNCTION_RETURN', functionName: 'print_n', returnValue: 'None' },
    },
    {
      step: 15, lineNum: 4,
      explanationEnglish: 'Returned from print_n(0). (Pop from Stack)',
      explanationHinglish: 'print_n(0) se wapas aaye. (Stack Pop)',
      memorySnapshot: { n: 1, CallStack: 'print_n(3) -> print_n(2) -> print_n(1)' },
      consoleOutput: '',
      animationEvent: { type: 'NONE' },
    },
    {
      step: 16, lineNum: 5,
      explanationEnglish: 'Print the current value of n (1).',
      explanationHinglish: 'Current value of n (1) print ki.',
      memorySnapshot: { n: 1, CallStack: 'print_n(3) -> print_n(2) -> print_n(1)' },
      consoleOutput: '1',
      animationEvent: { type: 'PRINT_VALUE', variableName: 'n', outputValue: 1 },
    },
    {
      step: 17, lineNum: 4,
      explanationEnglish: 'Returned from print_n(1). (Pop from Stack)',
      explanationHinglish: 'print_n(1) se wapas aaye. (Stack Pop)',
      memorySnapshot: { n: 2, CallStack: 'print_n(3) -> print_n(2)' },
      consoleOutput: '1',
      animationEvent: { type: 'NONE' },
    },
    {
      step: 18, lineNum: 5,
      explanationEnglish: 'Print the current value of n (2).',
      explanationHinglish: 'Current value of n (2) print ki.',
      memorySnapshot: { n: 2, CallStack: 'print_n(3) -> print_n(2)' },
      consoleOutput: '1\n2',
      animationEvent: { type: 'PRINT_VALUE', variableName: 'n', outputValue: 2 },
    },
    {
      step: 19, lineNum: 4,
      explanationEnglish: 'Returned from print_n(2). (Pop from Stack)',
      explanationHinglish: 'print_n(2) se wapas aaye. (Stack Pop)',
      memorySnapshot: { n: 3, CallStack: 'print_n(3)' },
      consoleOutput: '1\n2',
      animationEvent: { type: 'NONE' },
    },
    {
      step: 20, lineNum: 5,
      explanationEnglish: 'Print the current value of n (3).',
      explanationHinglish: 'Current value of n (3) print ki.',
      memorySnapshot: { n: 3, CallStack: 'print_n(3)' },
      consoleOutput: '1\n2\n3',
      animationEvent: { type: 'PRINT_VALUE', variableName: 'n', outputValue: 3 },
    }
  ],
};